### ISSUE TITLE
Adding a new point gives both a pin and point

### ISSUE THREAD

**Issue by gistin** [stevenpbachman/shinygeocat#66]
This messes up editing as the pin is not part of the analysis etc. Also probably causing #65

**Comment by gistin** [comment]
Adding new point seems to work, but you get both drop pin and a point. Need to get rid of dropped pin. Also editing (moving) these dropped pins cause a crash. I think the drop pin is getting added as a kind of separate layer. Probably assocated with map not updating.

**Comment by barnabywalker** [comment]
This is caused by the same things as #65 - the added marker position is added to the stored data frame of all points and then those points are plotted as circles.

I tried deleting the pin added by the toolbar but this didn't work, so ended up filtering user-added points before adding the stored data frame points to the map.
